### ISSUE TITLE
Push notification is showing up at 10:30 am

### ISSUE THREAD

**Issue by monoguerin** [oagarcia/penguin-report#13]
As a user I am getting the push notifications at 10:30 am  and double for the reminder of reporting my hours, no matter if I had already reported.

**Comment by oagarcia** [comment]
Will wait until tomorrow to recheck. I saw correct behavior today by 4:30PM

**Comment by oagarcia** [comment]
Closing as not related to error code. I was related to a local server instance also running the crons.
